language: python
python:
- 3.8
services: docker
before_install:
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
  | python -
install:
- poetry install
before_script:
- docker run -d -p 4444:4444 --shm-size 2g selenium/standalone-chrome
script:
- poetry run pytest --cov-config .coveragerc --cov pyasli tests
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- poetry build -f wheel
deploy:
  provider: script
  script: poetry publish -u __token__ -p $PYPI_PASSWORD
  on:
    tags: true
env:
  secure: OB5s78+++DFuYHMU6dx5nRvoDyQtnfS5IQfj+iiuLDtgCpPLx16KdQR759Ro3mITno456MYjyBpUzmCGJEMHdT/n64NNp3IaQ9haDyOyoJVTliXWC+81xi3JLpcfL2YyweQ+BSgqL+oNUfg/WzRvnjpLHFsn+DmyFFF7+dP4E+glPybvz+EOfj5k2npmAbgZXP0Bi+KYnhr8Br3+GzumnnVcKLtgXCvdVLV75s9a82KmCmSSeX13Nd2RKNNIiiviI6Z3zUWQNr9uw6H7G9iGquVp/PvfFN3AN+MuVgbfxrv+RokdSHZCp+vp7M2QQg3x7QO0isHnBQwVviyM5Qn5dmuAaf8lb9njOehtetNWANoFFVGanBkuPwm6nNlvqi53xAYFw7Qw12DHrUWoXlkUsTHZ54fNWZg3HIFdl5GYbXrNKPGru1yRrTbQQyN+G3cjUPXPxo7s4Thn6+mr/A5AM1MPvRTEY56sdmRtdceZ1e4pWsYJPmrIJBUgpaBe0fqYquYcSJBE0edVUhOsJpMWVdNpILIvXWXoVePaRdnUb1JjJSnC2Px+q+QDQDEb8DDezcidxv73s/aitH6k+O7y7HKfdQvcueq9cWcDZSjDh9i5J1DmgnCA4Ch4Hjw0OXc0atrEwxVHyTtDIxe0Udane/QMcS6w54s5hyPj7lWngNk=
