name: Check

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install
      - name: Run Pylint
        run: |
          poetry run pylint pyasli --exit-zero

  test:
    runs-on: ubuntu-latest
    services:
      test-internet:
        image: "gprestes/the-internet:v2.6.5"
        ports:
          - 7080:5000
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Pull chrome image
        run: |
          docker pull selenoid/chrome:latest
      - name: Run selenoid
        run: |
          docker run -d                                   \
          --name selenoid                                 \
          -p 4444:4444                                    \
          -v /var/run/docker.sock:/var/run/docker.sock    \
          -v $(pwd)/.selenoid/:/etc/selenoid/:ro              \
          aerokube/selenoid:latest-release
      - name: Install dependencies
        run: |
          poetry install
      - name: Show docker infrastructure
        run: |
          docker ps
          docker network ls
      - name: Run tests
        env:
          HOST: "localhost"
          BROWSER: "chrome"
          CI: "1"
          TARGET_HOST: "test-internet"
          TARGET_PORT: 7080
        run: |
          poetry run pytest -v --tb=line --cov-report xml --cov-config .coveragerc --cov pyasli tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
