name: Check

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install
      - name: Run Pylint
        run: |
          poetry run pylint pyasli --exit-zero

  test:
    runs-on: ubuntu-latest
    services:
      selenuim:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run pytest -v --tb=line --cov-config .coveragerc --cov pyasli tests
        env:
          HOST: "localhost"
          BROWSER: "chrome"
          CI: "1"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3