name: Check

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install
      - name: Run Pylint
        run: |
          poetry run pylint pyasli --exit-zero

  test:
    runs-on: ubuntu-latest
    services:
      the-internet:
        image: "gprestes/the-internet:v2.6.5"
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Pull chrome image
        run: |
          docker pull selenoid/chrome:latest
      - name: Download and start Selenoid
        run: |
          wget https://github.com/aerokube/selenoid/releases/download/1.10.10/selenoid_linux_amd64 -O selenoid
          chmod +x selenoid
          ./selenoid -version
          ./selenoid -conf '.selenoid/browsers.json' -container-network "${{ job.services.the-internet.network }}" start &
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        env:
          HOST: "localhost"
          BROWSER: "chrome"
          CI: "1"
          TARGET_HOST: "the-internet"
          TARGET_PORT: 5000
        run: |
          poetry run pytest -v --tb=line --cov-report xml --cov-config .coveragerc --cov pyasli tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
